[project]
name = "myproject-py4bdab2c2026q2-tomi"
version = "0.1.0"
description = "Homework 05: CI/CD and Docker"
authors = [
    { name = "Tomiris", email = "your_email@example.com" }
]
dependencies = [
    "click",
    "pytest",
]
requires-python = ">=3.11"

# Это критически важная часть, чтобы команда "python -m prime_pack_tomiris" работала
[project.scripts]
prime_pack = "prime_pack_tomiris.cli:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
